// model class representing a single transaction record
class TransactionModel {
  // id is optional because it is auto generated by sqlite
  final int? id;
  // amount spent or earned
  final double amount;
  // category like food, shopping, etc.
  final String category;
  // date stored as an iso string (example: 2025-11-05)
  final String date;
  // optional note or description
  final String? note;
  // flag to check if the transaction is a bill
  final bool isBill;

  // constructor for creating a transaction object
  TransactionModel({
    this.id,
    required this.amount,
    required this.category,
    required this.date,
    this.note,
    this.isBill = false,
  });

  // convert transaction object into a map for sqlite storage
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'amount': amount,
      'category': category,
      'date': date,
      'note': note,
      'isBill': isBill ? 1 : 0, // convert bool to int for sqlite
    };
  }

  // create a transaction object from a map retrieved from sqlite
  factory TransactionModel.fromMap(Map<String, dynamic> map) {
    return TransactionModel(
      id: map['id'],
      amount: map['amount'],
      category: map['category'],
      date: map['date'],
      note: map['note'],
      isBill: map['isBill'] == 1, // convert int back to bool
    );
  }
}
